### ISSUE TITLE
Copy Raw Text Without Formatting Option

### ISSUE THREAD

**Issue by CaptainPackers** [nicolasprigent/Dokuwiki-Copycode-plugin#10] opened 2022-02-25 16:10 UTC
I love this plugin, but I wish there was an option to copy raw text without formatting. Whenever I drop the content of the copy/paste buffer into an sql window (DbVisualizer), a non-printing character is embedded before the text that makes the parser choke. When I examine it in a hex editor I see all kinds of embedded formatting. (It's a bit puzzling to me how so much information can be embedding in a single non-printing character.) It is possible to simply delete the character and run the query, but if it is a multi-query script I have to hunt them all down and delete them. It would make this plugin so much more convenient if I could just check a checkbox in the configuration file to copy raw text without formatting.

Thanks

**Comment by nicolasprigent** [comment] 2022-02-25 16:50
Hello captain, glad you found the plugin useful.
I also found out sometimes in some of my stored code snippets some carriage return characters that were not interpreted well by php getting it to bug. I edited them and I were fine. 
I think it can also be a character coded in a certain way in the program you use to write the code, then coded differently when stores in dokuwiki document, then when copied back the wrong html coded character is sent...
I'm not sure how to make my code copy only plain text instead of formatted one, but I'll surely investigate.
Don't you think left click for usual copy and right click for plain text copy would be a valid option for you? Could you send me a text file containing the wrong invisible character?

**Comment by CaptainPackers** [comment] 2022-02-25 22:56
I do like the left click, right click options.

I will send you the sample next week as my work week has now ended.

**Comment by nicolasprigent** [comment] 2022-02-28 07:59
I investigated on my side, the copied code is already raw code. I think that what I suggested (left or right click) wouldn't be the solution, there should be an option in the plugin to sanitize some characters from a list I guess. Not the real purpose of the plugin but can be a workaround. I think that the code on your dokuwiki is having this character too (but I may be wrong). You should check your saved dokuwiki script and see if when you copy it, then delete the problematic character and save the working code back in dokuwiki you still have the problem.

**Comment by CaptainPackers** [comment] 2022-02-28 16:25
Nicolas,

When I type the raw text below between the lines with +++ into dokuwiki (note that there are no extra characters on the line between the select statements)

+++
select sysdate from dual;

select sysdate from dual@test;`
+++

and then use the copy function of your plugin and paste it into a text editor like Kate or Gedit, an extra character appears on the line between the statements. If I then copy and paste that character into a hex editor, it shows that the character is C2A0. I find that pretty strange. I was expecting it to be a carriage return and line feed, which I could easily search and replace with regular expressions, but this is not even a valid ASCII character. So I don't know what it is, where it comes from, or how to deal with it other than a manual search and destroy in my query editor prior to running my queries.

I can work around it, but it's a bit of a nuisance.

The code below has the extra character on the line between the two statements.

+++
select sysdate from dual;
 
select sysdate from dual@berp;
+++

I appreciate your taking the time to look at this.

**Comment by nicolasprigent** [comment] 2022-02-28 20:49
Ok I've got a working code now (not in github for now). It deletes all \u00A0 characters. They are appearing for no reason, my guess is when there's multiple carriage returns, it appens. It's maybe too drastic, but this character is not really intended to be used in a development code as it's not a valid ascii. Too much problems, so fire is the solution 🔥 

 I've also implemented something for the right button, I'd like to know if that should be usefull for you : it replaces all cariage returns with "normal" spaces. So now, left click will send this as intended :
+++
select sysdate from dual;

select sysdate from dual@test;`
+++

and right click would send this :

+++
select sysdate from dual;  select sysdate from dual@test;`
+++

Would you like to have this feature too ?
There's still the middle mouse button if you want a third option 😄

**Comment by CaptainPackers** [comment] 2022-03-01 20:36
I would probably only use the first option, where the line spacing ins preserved and  \u00A0 is removed. But thanks for offering to go the extra mile.

Thanks for the quick response. I look forward to seeing the new release on github.

**Comment by nicolasprigent** [comment] 2022-03-02 15:15
The plugin is ready to be updated. Keep me in touch if it works ok for you, I'll then close this issue.

**Comment by CaptainPackers** [comment] 2022-03-02 15:39
I will try to test it today and get back to you.

Thanks

**Comment by CaptainPackers** [comment] 2022-03-03 21:49
Works like a charm! Thank you so much for resolving this so quickly.

**Comment by nicolasprigent** [comment] 2022-03-04 07:05
You're welcome! Don't hesitate to ask if you've got new problems or find an idea for future development.

**Closed as completed by nicolasprigent** 2022-03-04 07:05 UTC
